services:
  web:
    build:
      context: .
      args:
        HOSTUID: ${HOSTUID}
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - PROXY_URL_FOR_IMGIX=${PROXY_URL_FOR_IMGIX}
    ports:
      - 8000:8000
    volumes:
      - ./:/app:rw
  imgproxy:
    image: darthsim/imgproxy:latest
    ports:
      - 8080:8080
    env_file:
      - .env
  thumbor:
    image: minimalcompact/thumbor
    ports:
      - 8888:80
