services:
  web:
    build:
      context: .
      args:
        HOSTUID: ${HOSTUID}
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - PROXY_URL=${PROXY_URL}
    ports:
      - 8000:8000
    volumes:
      - ./:/app:rw
  imgproxy:
    image: darthsim/imgproxy:latest
    ports:
      - 8080:8080
    env_file:
      - .env
